# Generated by Django 2.2.12 on 2020-06-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=30)),
                ('disc', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('distance', 'Distance Driver'), ('fairway', 'Fairway Driver'), ('midrange', 'Midrange'), ('putter', 'Putter')], max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='static/common/img/')),
                ('stamp', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('stability', models.CharField(choices=[('very overstable', 'Very Overstable'), ('overstable', 'Overstable'), ('stable', 'Stable'), ('understable', 'Understable')], max_length=30)),
                ('plastic_type', models.CharField(max_length=30)),
                ('plastic_grad', models.CharField(max_length=30)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('everyone', 'Everyone')], max_length=30)),
                ('speed', models.IntegerField()),
                ('glide', models.IntegerField()),
                ('turn', models.IntegerField()),
                ('fade', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('diameter', models.DecimalField(decimal_places=1, max_digits=5)),
                ('height', models.DecimalField(decimal_places=1, max_digits=5)),
                ('rim_depth', models.DecimalField(decimal_places=1, max_digits=5)),
                ('rim_width', models.DecimalField(decimal_places=1, max_digits=5)),
                ('manufacturer_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scaled_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('collectors', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
