# Generated by Django 2.2.12 on 2020-06-16 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plastic',
            fields=[
                ('plastic_id', models.AutoField(primary_key=True, serialize=False)),
                ('plastic_type', models.CharField(max_length=40)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Manufacturer')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='plastic_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Plastic'),
        ),
    ]
