# Generated by Django 2.2.12 on 2020-06-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200616_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stamp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
